version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  REACT_APP_SERVER_HOST: http://localhost
  REACT_APP_SERVER_PORT: 8000

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    restart: unless-stopped
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always
  server:
    build: ./server
    container_name: node_server_container
    depends_on:
      - mysql-db
    environment:
      CHOKIDAR_USEPOLLING: "true"
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8000:8000
    links:
      - mysql-db
    command: yarn start
  client:
    build: ./client
    container_name: client_container
    environment:
      CHOKIDAR_USEPOLLING: "true"
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    links:
      - server
    command: yarn start